name: To Do List App
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build
        run: ./gradlew assemble
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Run tests
        run: ./gradlew clean test