name: Pull request workflow
on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
jobs:
  pull-request:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ToDoList
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        #with:
        #  cache: 'gradlew'
      - name: Lint
        run: ./gradlew detekt
      - name: Build
        run: ./gradlew assemble
      - name: Tests
        run: ./gradlew clean test
