name: Pull request workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew assemble
      - name: Set up database
        uses: ikalnytskyi/action-setup-postgres@v5
        run:
          su - postgres
          createdb ToDoListDBTest
          psql -c "ALTER USER postgres WITH PASSWORD 'postgres'"
        shell: bash
      - name: Test
        run: ./gradlew clean test